import type { REGION_CONFIG as RegionConfig } from './regions'
import { SeededRandom } from './seed'
import { OpenSimplexNoise } from './noise'
import type { Grid } from './types';
import type { GameSettings } from '../../game/GameScene';
import type { ChunkSettings } from './chunk';

// dynamic settings
export type RiverSetting = {
    name: string,
    count: number,
    bedWidth: number, // in tiles
    windiness: number, // 0 straight -> 2.5 extroime
    genThreshold: number, // The amount to randomly vary the river cout with
};


export interface GlobalGenerationMeta {
    maxX: number,
    maxY: number,
    maxRadius: number,
    bufferFactor: number,
    bufferX: number,
    bufferY: number,
    centerX: number,
    centerY: number,
    stretchX: number,
    stretchY: number,
    oceanClamp: number,
    mOffsetX: number;
    mOffsetY: number;
    cosA: number;
    sinA: number;
}

export class MapGenerator {
    static DEFAULT_SEED = 'aborio rice';

    // @TODO: adjust it so that the world size is by default 256*256 chunks (12800*12800)
    static generateGlobalMetadata(config: GameSettings, rng: SeededRandom): GlobalGenerationMeta {
        if (!rng) {
            throw new Error('We need an rng instance!')
        }

        const randomAngle = rng.nextRange(0, Math.PI * 2);
        // @NOTE this is where the GenerationSettings should overwrite & split between this & ChunkSettings 
        const maxX = config.maxX || 750;
        const maxY = config.maxY || 750;
        const centerX = maxX / 2;
        const centerY = maxY / 2;
        const bufferFactor = 0.05;
        const oceanClamp = 0.85;

        return {
            maxX,
            maxY,
            maxRadius: Math.sqrt(centerX * centerX) * oceanClamp,
            bufferFactor,
            bufferX: maxX * bufferFactor,
            bufferY: maxY * bufferFactor,
            centerX,
            centerY,
            stretchX: 0.7,
            stretchY: 1.3,
            oceanClamp,
            mOffsetX: rng.nextRange(10000, 90000),
            mOffsetY: rng.nextRange(10000, 90000),
            cosA: Math.cos(randomAngle),
            sinA: Math.sin(randomAngle),
        }
    }

    // CLIMATE:
    // - Create climate system so that I can tell where certain features should spawn

    // LAKES: 
    // - All enclosed bodies of water inside land must be redesignated as LAKE
    // - Some small local depressions can be made at across the map. Also, isolated landlocked BEACH will be carved out as a BASIN 
    // - If the climatic conditions suit, fill a BASIN with water.
    // - Lakes of a particular altitude can become river sources (these don't include lakes later generated by rivers)

    // RIVERS:
    // - Source from high altitude tiles (MOUNTAIN, or HILL) or as the edge tile of basin LAKEs
    // - The larger the lake, the more likely it will spawn a river
    // - Create major rivers which then have minor tributaries flowing out of them
    // - Rivers below HILLS will later get wrapped in RIVERBANK tiles
    // - Rivers should path with the following priorities:
    // - 1. Check if it can move downhill
    // - 2. If nowhere to move downhill exists, check if the river has ended up in a basin and fill it with LAKE.
    // - 3. If no basin, find the nearest OCEAN tile. Then...
    // -     3.1. check if that path is crossed by a HILL, if it is, snake toward the hill on encountering the hill,
    // -     3.2. if we encounter the hill, do the basin check/fill. if no hill is there, snake toward the OCEAN, until elevation resumes downhill
    // -     3.3. If a basin fill was successful on terminating against a hill and the river is MAJOR, carve snaking a canyon through it until we reach PLAIN.
    // - 4. If a MAJOR river has terminated in a LAKE, pick the lowest altitude tile on the opposing half of the LAKE body and begin a new MINOR river from there using these same rules


    ///////////////////////////////
    //     UTILITY FUNCTIONS     //
    ///////////////////////////////
    // POSSIBLY DEPRECATED
    // find the vector from a tile to the nearest tile of a type of REGION
    static findNearestTileVector(sx: number, sy: number, width: number, height: number, grid: Grid, findingRegion: RegionConfig): { x: number, y: number } | null {
        const queue: { x: number, y: number }[] = [{ x: sx, y: sy }];
        const visited = new Set<string>([`${sx},${sy}`]);
        const scanDirs = [{ dx: 0, dy: -1 }, { dx: 0, dy: 1 }, { dx: -1, dy: 0 }, { dx: 1, dy: 0 }];
        let head = 0;

        while (head < queue.length && queue.length < 1500) {
            const curr = queue[head++];
            if (grid[curr.x][curr.y].region.name === findingRegion.name) return curr;

            for (const d of scanDirs) {
                const nx = curr.x + d.dx, ny = curr.y + d.dy;
                if (nx >= 0 && nx < width && ny >= 0 && ny < height) {
                    const key = `${nx},${ny}`;
                    if (!visited.has(key)) { visited.add(key); queue.push({ x: nx, y: ny }); }
                }
            }
        }
        return null;
    }

    // Attempt to detect whether the current selected tile is within a basin.
    static detectBasin(sx: number, sy: number, width: number, height: number, grid: Grid): { x: number, y: number }[] | null {
        const queue: { x: number, y: number }[] = [{ x: sx, y: sy }];
        const visited = new Set<string>([`${sx},${sy}`]);
        const startElevation = grid[sx][sy].elevation;
        const scanDirs = [{ dx: 0, dy: -1 }, { dx: 0, dy: 1 }, { dx: -1, dy: 0 }, { dx: 1, dy: 0 }];

        let head = 0;
        while (head < queue.length) {
            const curr = queue[head++];
            if (queue.length > 200) return null;

            for (const d of scanDirs) {
                const nx = curr.x + d.dx, ny = curr.y + d.dy;
                if (nx < 0 || nx >= width || ny < 0 || ny >= height) return null;

                const key = `${nx},${ny}`;
                if (visited.has(key)) continue;
                visited.add(key);

                if (grid[nx][ny].elevation < startElevation - 0.01) return null;
                if (grid[nx][ny].elevation <= startElevation + 0.02) { queue.push({ x: nx, y: ny }); }
            }
        }
        return queue;
    }

    // NOISE GENERATION
    static getDomainWarpedSample(
        x: number,
        y: number,
        mOffsetX: number,
        mOffsetY: number,
        settings: ChunkSettings,
        noise: OpenSimplexNoise,
    ): { sampleX: number, sampleY: number } {
        const warpX = noise.noise2D((x + 200) * 0.018, (y + 200) * 0.018) * 45;
        const warpY = noise.noise2D((x - 200) * 0.018, (y - 200) * 0.018) * 45;

        const sampleX = (x + mOffsetX + warpX) * settings.macroScale;
        const sampleY = (y + mOffsetY + warpY) * settings.macroScale;

        return { sampleX, sampleY };
    }

    // Fractional Brownian Motion for ridged multi-fractal noise structures
    // This is scienceish for forked mountain range structures.
    static getRidgedfBm(nx: number, ny: number, octaves: number, noise: OpenSimplexNoise): number {
        let value = 0;
        let amplitude = 1.0;
        let frequency = 1.0;
        let maxValue = 0;

        for (let i = 0; i < octaves; i++) {
            // Signal inversion maps absolute valleys into sharp ridged spines
            let signal = noise.noise2D(nx * frequency, ny * frequency);
            signal = 1.0 - Math.abs(signal);

            // Square the signal to sharpen the peak crests
            signal = signal * signal;

            value += signal * amplitude;
            maxValue += amplitude;

            frequency *= 2.15;  // Lacunarity
            amplitude *= 0.5;  // Persistence
        }
        return value / maxValue;
    }

    // Standard fBm for organic landmass foundational plateaus
    // More science language for when plains form outwards from mountain ridges.
    static getStandardfBm(nx: number, ny: number, octaves: number, noise: OpenSimplexNoise): number {
        let value = 0;
        let amplitude = 1.0;
        let frequency = 1.0;
        let maxValue = 0;

        for (let i = 0; i < octaves; i++) {
            const signal = (noise.noise2D(nx * frequency, ny * frequency) + 1.0) / 2.0;
            value += signal * amplitude;
            maxValue += amplitude;
            frequency *= 2.0;
            amplitude *= 0.54;
        }
        return value / maxValue;
    }

    // IMPROVEMENTS
    // DECOUPLED FEATURE MASKING
    // DYNAMIC THRESHOLDING
}
